#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2018 Jaan Toots <jaan@jaantoots.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

source ~/.config/i3blocks/environment

#------------------------------------------------------------------------

load="$(cut -d ' ' -f1 /proc/loadavg)"
color="$(echo "$load" "$(nproc)" "$base08" |
    awk '$1 > $2 {print $3;}')"

long() {
    load="$(cut -d ' ' -f-3 /proc/loadavg)"
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
    1) long ;;  # left click
    3) term -e htop >/dev/null ;;  # right click
esac

echo "$load_icon $load"
echo "$load"
echo "$color"
